version: '3'
services:
  localdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: localdbpassword
      POSTGRES_USER: puser
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
  devenv:
    build: .
    restart: always
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 1337:1337
      - 5173:5173
      - 8822:22
    depends_on:
      - localdb
    volumes:
      - ${HOME}/share:/root/share
      - vroot:/root
volumes:
  vroot:
