# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = '\[ $directory\]$character'
right_format = '$time $git_branch $git_status $git_commit $git_commit'

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red) '

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 2
truncation_symbol = '…/'
fish_style_pwd_dir_length = 3

[time]
disabled = false
